version: "2"
authtoken: 39uz90VyjnTXMVcZnaROckeU33W_afVGiAHKKyPEvLAvnZsm
tunnels:
  k8s-api:
    proto: http
    addr: 8011
  logs-api:
    proto: http
    addr: 8012
  metrics-api:
    proto: http
    addr: 8013
  runbooks-api:
    proto: http
    addr: 8014
